### ISSUE TITLE
Dark broken on Windows

### ISSUE THREAD

**Issue by janpio** [wilfredwee/photon-australis#3] opened 2017-11-14 16:50 UTC
Just tried all three files and dark looked like this for me: 
![image](https://user-images.githubusercontent.com/183673/32792646-2dd278f2-c964-11e7-9fa4-58a54221ee76.png)

Win10, FF57

**Comment by jasonbassford** [comment] 2017-11-14 17:37
Default does the same thing too.

**Comment by janpio** [comment] 2017-11-14 17:49
Interesting, for me bot default and light work as intended.

**Comment by jasonbassford** [comment] 2017-11-14 17:59
My mistake! I must have done something stupid—mistakenly having the dark CSS code in use when using the default theme. (I just copied / pasted the default code again, and it is, indeed, working.) Without user error, I can confirm that it's only the dark that's broken.

**Comment by credomane** [comment] 2017-11-14 18:43
Do believe I fixed the dark theme. It was missing two entries for transparent background. Here is a GIST of the fixed css https://gist.github.com/credomane/5c43e64ac68f742804a8d32460a0e576

The revisions show the two changes I made.

**Comment by wilfredwee** [comment] 2017-11-15 08:12
@credomane Is the background not transparent by default? From my testing it's already transparent.

Based on the discussion on this thread, is this a non-issue?

Can this issue be closed?

**Comment by credomane** [comment] 2017-11-15 15:00
> Is the background not transparent by default?

Based on a commit comment you are using the FF58+ nightlies. It might be possible the backgrounds *is* transparent by default there but us using the FF57 release it is not. Until I made the changes in my GIST the dark theme looks like the picture in the first comment. White square borders around the active tab.

>Based on the discussion on this thread, is this a non-issue?

It is certainly an issue; for FF57 users at least. The whole discussion has been "photon-australis Dark theme" + FF57 == white borders on tabs. How can this possibly be a non-issue?

**Comment by wilfredwee** [comment] 2017-11-15 18:17
The picture on the first post is the result of using `userChrome-dark.css` in the default theme. 

You are right though, the background is not transparent by default, making it transparent solves some other problem. I'll add a new release for that soon.

**Comment by wilfredwee** [comment] 2017-11-16 07:59
Thanks for the feedback and pointing out a potential solution!
This release should fix this: https://github.com/wilfredwee/photon-australis/releases/tag/v0.2.2

I'll close this for now but feel free to re-open if there's something else.

**Closed by wilfredwee** 2017-11-16 07:59 UTC
