### ISSUE TITLE
Rounded Tabs for Thunderbird

### ISSUE THREAD

**Issue by tascholl** [wilfredwee/photon-australis#79] opened 2019-10-22 01:44 UTC
I just upgraded to Thunderbird 60.9 from version 52.  Thunderbird 60.9 now has squared tabs instead of the rounded ones.  I tried using the userChrome-default.css for Firefox but it does not work for Thunderbird 60.9.  Is there one available that will work for Thunderbird? 

Thanks in advance. 
Tim

**Comment by wilfredwee** [comment] 2019-10-23 05:29
I've looked into Thunderbird and it's not trivial to implement. I don't have the time to do it right now, but feel free to contribute. Resolving as duplicate of: #51

**Closed by wilfredwee** 2019-10-23 05:29 UTC

**Comment by tascholl** [comment] 2019-10-25 23:49
Thanks for the reply.  Yes that was my thought as well, and beyond my level
of expertise.
