### ISSUE TITLE
Pin tabs being cutt-off when there are many tabs with scrolling buttons

### ISSUE THREAD

**Issue by phuphung-amblique** [wilfredwee/photon-australis#75] opened 2019-09-04 04:18 UTC
Hi, 
I found a small issues with tab toolbar:
1). With latest Firefox update, there is border bottom on each inactive tab.
2). I have many open tabs (pin tabs vs. normal tab) and there are scrolling buttons, 
when I click on pin tabs, the height of Tab toolbar change which cause pin tabs content being cut off.
Tab toolbar height return to normal when I click on normal tabs.
Pls help to fix those issue ASAP, thanks.

System Info:
Windows 10 64bit
Firefox 69 - Light theme
Photon Australis - Light theme

![1](https://user-images.githubusercontent.com/44799686/64225455-b5006980-cf05-11e9-8f92-b6fb2b4675e6.jpg)
![2](https://user-images.githubusercontent.com/44799686/64225456-b5006980-cf05-11e9-992d-fd97c33b2be3.jpg)

**Comment by wilfredwee** [comment] 2019-09-07 07:53
Hi there, the first issue is fixed in the latest release https://github.com/wilfredwee/photon-australis/releases/latest

The 2nd issue is harder to solve and probably won't happen anytime soon.

Thanks.

**Comment by wilfredwee** [comment] 2019-09-07 07:59
Closed as duplicate of #72

**Closed by wilfredwee** 2019-09-07 07:59 UTC
